// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_h7u3uzpAyC1Mzgq9f8iCN7OQ3g1fJg',
    appId: '1:463224511599:web:132052dacf864ccd0dc19a',
    messagingSenderId: '463224511599',
    projectId: 'learn-firebase-b01df',
    authDomain: 'learn-firebase-b01df.firebaseapp.com',
    databaseURL: 'https://learn-firebase-b01df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-b01df.appspot.com',
    measurementId: 'G-LTCSTQ2LY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xN74IkYeH8hOwK9bnhj6_AWfjyk2YxU',
    appId: '1:463224511599:android:571c78c9d4391c560dc19a',
    messagingSenderId: '463224511599',
    projectId: 'learn-firebase-b01df',
    databaseURL: 'https://learn-firebase-b01df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-b01df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJoAsvnB9doSMRzq_hfcyEudKT_xaa7o',
    appId: '1:463224511599:ios:34543b01058102190dc19a',
    messagingSenderId: '463224511599',
    projectId: 'learn-firebase-b01df',
    databaseURL: 'https://learn-firebase-b01df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-b01df.appspot.com',
    iosBundleId: 'com.example.firebaeFirestoreProject',
  );
}
